### ISSUE TITLE
word-break on small screens

### ISSUE THREAD

**Issue by KhodorAmmar** [reactjs/reactjs.org#1024]
Is there a reason `<h3>` have a `word-break: break-all;` on small screens? I feel it makes the headers a little bit harder to read

<img width="367" alt="screen shot 2018-06-30 at 2 30 32 pm" src="https://user-images.githubusercontent.com/854420/42124357-29843274-7c72-11e8-800c-d27dfa3eca05.png">

css in question:

```css
@media (max-width: 599px) {
  .css-51kfyg h3, [data-css-51kfyg] h3 {
      word-break: break-all;
  }
}
```
