### ISSUE TITLE
[Beta] Incorrect font weight

### ISSUE THREAD

**Issue by yousefelgoharyx** [reactjs/reactjs.org#5443]
This is the current font weight of paragraphs in the beta docs
![image](https://user-images.githubusercontent.com/30435916/211114608-d23df1d4-0ce9-4830-b57d-bb3d2227c591.png)
The computed styles have a font weight of 400 but it is actually 500 because there is no font face for the regular font. there is only a font face for the font of weight 500 and this can be found in `index.css` that only has the following font faces:

```css
@font-face {
    font-family: 'Source Code Pro';
    font-style: normal;
    font-weight: 400;
    font-display: swap;
    src: url('/fonts/Source-Code-Pro-Regular.woff2') format('woff2');
  }

  @font-face {
    font-family: 'Optimistic Display';
    src: url('https://beta.reactjs.org/fonts/Optimistic_Display_W_Lt.woff2')
      format('woff2');
    font-weight: 300;
    font-style: normal;
    font-display: swap;
  }

  @font-face {
    font-family: 'Optimistic Display';
    src: url('https://beta.reactjs.org/fonts/Optimistic_Display_W_Md.woff2')
      format('woff2');
    font-weight: 500;
    font-style: normal;
    font-display: swap;
  }

  @font-face {
    font-family: 'Optimistic Display';
    src: url('https://beta.reactjs.org/fonts/Optimistic_Display_W_Bd.woff2')
      format('woff2');
    font-weight: 700;
    font-style: normal;
    font-display: swap;
  }
```

The solution would be to add a font face for the regular font because the current font weight for the paragraphs is a bit unreadable.
